exclude: |-
  ^(.*/node_modules/|remip-client/dist/|remip/dist/|.*\.lock$)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
  - repo: local
    hooks:
      # 変更されたファイルに関連するテストとlintを実行
      - id: test-changed-files
        name: test-changed-files
        entry: bash -c './scripts/test-changed-files.sh staged'
        language: system
        pass_filenames: false
        always_run: false
